### PR TITLE
fix(component): updates for org name change to stolostron

### PR DESCRIPTION
**Pull request by mark-nc**
Minor changes for org name change from open-cluster-management to stolostron

re #18716

### CODE REVIEW

**Comment by mark-nc** [comment]
The build for this PR is failing at the step that tries to clone and build the `kui-web-terminal` image to run the tests.  That is failing as one script in the `kui-web-terminal` build is failing due to the org rename so the org rename changes need to be completed in that repo first before trying this build again.

**Comment by mark-nc** [comment]
For https://github.com/stolostron/backlog/issues/18716

**Comment by mark-nc** [comment]
The build now completes and the tests all pass.

**Review by zlayne — APPROVED** [review]

**Review by jlpadilla — COMMENTED** [review]
/lgtm

**Pull request merged**
